// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://saillvmcvrsnprjfffyh.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InNhaWxsdm1jdnJzbnByamZmZnloIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDMwOTg0ODgsImV4cCI6MjA1ODY3NDQ4OH0.P9f_1VDwy9UBsMsmdOyH_XEBzYb2Ts19AyNTGZ1Yu2s";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);